# Generated by Django 5.1.1 on 2024-11-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collec_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Collec',
        ),
    ]
